Eddie.playbooks['master'] = {
  id: 'master',
  title: 'Master Entry Point',
  subtitle: 'Main routing & triage flow',
  status: 'active',
  color: 'var(--green)',
  group: 'entry',
  keywords: [],
  markdown: [
    '---',
    'title: Master Entry Point',
    'subtitle: Main routing & triage flow',
    'status: active',
    '---',
    '',
    '## Step 1: Greet & Classify Issue',
    '',
    ':::eddie',
    'Hi there! I\'m Eddie, your internet support assistant. I\'m here to help get you sorted. Could you tell me a bit about what\'s going on — are you experiencing any of the following?',
    ':::',
    '',
    '- No internet at all → Step 2',
    '- Slow internet → Step 2',
    '- One device only → Step 2',
    '- Wi-Fi issues → Step 2',
    '- IPTV / Streaming → Step 2',
    '',
    ':::internal',
    'Classify into one of: **No Internet**, **Slow Internet**, **One Device Only**, **Wi-Fi Issues**, **IPTV/Streaming**.',
    ':::',
    '',
    '## Step 2: Identify Connection Type',
    '',
    ':::eddie',
    'Thanks for that. Just so I can point you in the right direction — do you know if your connection is fibre or wireless?',
    ':::',
    '',
    '- Fibre → Ask: Zoom Fibre or Openserve?',
    '- Wireless → Route using table below',
    '',
    ':::internal Splynx check',
    'Check Splynx first before routing:',
    '',
    '• If account is **blocked** → inform client of disconnection + outstanding balance. If payment terms wanted → pass to human agent.',
    '• Splynx labels: {blue|Uncapped ZF / ZoomFibre} = Zoom Fibre, {blue|WTTH} = Wireless, {blue|OpenServe} = Openserve.',
    ':::',
    '',
    '### Routing Table',
    '',
    '| Issue | Connection Type | Route To |',
    '|-------|----------------|----------|',
    '| No Internet | Zoom Fibre | [[a|Playbook A]] |',
    '| No Internet | Openserve | [[b|Playbook B]] |',
    '| No Internet | Wireless | [[c|Playbook C]] |',
    '| Slow Internet | Any | [[d|Playbook D]] |',
    '| One Device Only | Any | [[e|Playbook E]] |',
    '| Wi-Fi Issues | Any | [[f|Playbook F]] |',
    '| IPTV / Streaming | Any | [[g|Playbook G]] |'
  ].join('\n')
};
