Eddie.playbooks['e'] = {
  id: 'e',
  title: 'Playbook E — One Device Only',
  subtitle: 'Single device troubleshooting',
  status: 'active',
  color: 'var(--green)',
  group: 'playbooks',
  keywords: ['one device', 'single device', 'laptop', 'phone', 'tablet', 'smart TV'],
  markdown: [
    '---',
    'title: Playbook E — One Device Only',
    'subtitle: Single device troubleshooting',
    'status: active',
    'keywords: one device, laptop, phone, tablet, smart TV',
    '---',
    '',
    '## Step 1: Confirm Only One Device Affected',
    '',
    ':::eddie',
    'Just to make sure — is it only one device that\'s having trouble, or are all your devices affected?',
    ':::',
    '',
    '- All devices affected → Redirect to [[master|No Internet playbook]]',
    '- One device only → Step 2',
    '',
    '## Step 2: Identify Device Type',
    '',
    ':::eddie',
    'What type of device is it? Phone, laptop, desktop, smart TV, or tablet?',
    ':::',
    '',
    ':::internal',
    'Note the device type — it\'ll be needed if this escalates.',
    ':::',
    '',
    '## Step 3: Restart Device',
    '',
    ':::eddie',
    "Let's try a quick restart. Switch off your device completely, wait about 10–20 seconds, then turn it back on and test your internet. Let me know how it goes.",
    ':::',
    '',
    '- Working → ✅ RESOLVED',
    '- Still not working → Step 4',
    '',
    '## Step 4: Reconnect Wi-Fi',
    '',
    ':::eddie',
    'Try turning your Wi-Fi off and back on. Then select your network and enter the password again. Give it a moment and let me know if it connects.',
    ':::',
    '',
    '- Working → ✅ RESOLVED',
    '- Still not working → Step 5',
    '',
    '## Step 5: Forget & Reconnect Network',
    '',
    ':::eddie',
    "Let's try forgetting the network entirely. Go to your Wi-Fi settings, find your network name, tap \"Forget\" or \"Remove\", then reconnect by selecting it again and entering your password.",
    ':::',
    '',
    '- Working → ✅ RESOLVED',
    '- Still not working → Step 6',
    '',
    '## Step 6: Test Other Apps / Websites',
    '',
    ':::eddie',
    "Can you try opening a different website or app? For example, if YouTube isn't working, try Google or a news site. Does anything else load?",
    ':::',
    '',
    '- Other sites work → App-specific issue — advise client it may be the app/site',
    '- Nothing works → Step 7',
    '',
    '## Step 7: Move Closer to Router',
    '',
    ':::eddie',
    'Can you try moving closer to your router — ideally in the same room — and test again? Sometimes walls and distance can weaken the signal.',
    ':::',
    '',
    '- Works when closer → Signal/range issue — suggest Wi-Fi extender',
    '- Still not working → Step 8',
    '',
    '## Step 8: Escalate',
    '',
    ':::eddie',
    "We've tried a few things and it's still not playing along. Let me get one of our team members to take a closer look. Just need a few details first:",
    ':::',
    '',
    ':::internal Collect',
    '• Name',
    '• Contact number',
    '• Service address',
    '• Device type and model',
    '• Any error messages shown',
    ':::',
    '',
    '{red|Escalate-DeviceIssue}'
  ].join('\n')
};
