Eddie.playbooks['f'] = {
  id: 'f',
  title: 'Playbook F — Wi-Fi Issues',
  subtitle: 'Connection & signal troubleshooting',
  status: 'active',
  color: 'var(--green)',
  group: 'playbooks',
  keywords: ['Wi-Fi', 'wifi', 'signal', 'dropping', 'disconnecting', "can't connect"],
  markdown: [
    '---',
    'title: Playbook F — Wi-Fi Issues',
    'subtitle: Connection & signal troubleshooting',
    'status: active',
    "keywords: Wi-Fi, signal, dropping, disconnecting, can't connect",
    '---',
    '',
    '## Step 1: Connected but No Internet vs Cannot Connect',
    '',
    ':::eddie',
    'Just to clarify — when you say Wi-Fi issues, are you connected to Wi-Fi but have no internet, or can you not connect to the Wi-Fi network at all?',
    ':::',
    '',
    '- Connected but no internet → Redirect to [[master|No Internet playbook]]',
    '- Cannot connect at all → Step 2',
    '',
    '## Step 2: One Device or Multiple?',
    '',
    ':::eddie',
    'Is this happening on just one device or on multiple devices?',
    ':::',
    '',
    '- One device → Follow [[e|Playbook E]] steps',
    '- Multiple devices → Step 3',
    '',
    '## Step 3: Check Distance from Router',
    '',
    ':::eddie',
    "How far are you from your router? If you're in a different room, can you try moving closer — ideally right next to it — and see if you can connect?",
    ':::',
    '',
    '- Works when closer → Range issue — suggest extender',
    '- Still not working next to router → Step 4',
    '',
    '## Step 4: Restart Router',
    '',
    ':::eddie',
    "Let's restart the router. Switch it off, wait 30 seconds, switch it back on, and wait 2–3 minutes. Then try connecting again.",
    ':::',
    '',
    '- Working → ✅ RESOLVED',
    '- Still not working → Step 5',
    '',
    '## Step 5: Forget & Reconnect Network',
    '',
    ':::eddie',
    'On your device, go to Wi-Fi settings, find your network, tap "Forget" or "Remove", then reconnect by selecting it and entering the password again.',
    ':::',
    '',
    '- Working → ✅ RESOLVED',
    '- Still not working → Step 6',
    '',
    '## Step 6: Escalate',
    '',
    ':::eddie',
    "We've tried a few things and it's still not connecting. Let me get our technical team to investigate. Just need a few details:",
    ':::',
    '',
    ':::internal Collect',
    '• Name',
    '• Contact number',
    '• Service address',
    '• Which devices are affected',
    '• Distance from router tested',
    '• Whether router was restarted',
    ':::',
    '',
    ':::warn Never',
    'Never ask the client to open equipment, change router settings, or adjust antennas.',
    ':::',
    '',
    '{red|Escalate-WiFi}'
  ].join('\n')
};
