Eddie.playbooks['a'] = {
  id: 'a',
  title: 'Playbook A — No Internet · Zoom Fibre',
  subtitle: 'ZTE router / LOS-PON diagnosis',
  status: 'active',
  color: 'var(--green)',
  group: 'playbooks',
  keywords: ['no internet', 'LOS', 'PON', 'fibre is down', 'red LOS light', 'ZTE router', 'Zoom Fibre'],
  markdown: [
    '---',
    'title: Playbook A — No Internet · Zoom Fibre',
    'subtitle: ZTE router / LOS-PON diagnosis',
    'status: active',
    'keywords: no internet, LOS, PON, fibre is down, red LOS light, ZTE router, Zoom Fibre',
    '---',
    '',
    ':::warn Do NOT use for',
    'Wireless connections or Openserve fibre. Route those to [[c|Playbook C]] or [[b|Playbook B]] respectively.',
    ':::',
    '',
    '## Step 1: Confirm Reboot',
    '',
    ':::eddie',
    "Let's start with a quick reboot of your router. Can you switch it off at the power, wait about 30 seconds, then switch it back on? Give it 2–3 minutes to fully start up and let me know if your internet comes back.",
    ':::',
    '',
    '- Back online → ✅ RESOLVED',
    '- Still offline / already rebooted → Step 2',
    '',
    '## Step 2: Check LOS / PON Lights',
    '',
    ':::eddie',
    "Thanks for trying that. Can you take a look at the front of your ZTE router — do you see any lights labelled LOS or PON? Let me know what colour they are (red, green, or off).",
    ':::',
    '',
    '- Red LOS light → Step 3A',
    '- Green PON (flashing or solid) → Step 3B',
    '- Unclear / can\'t tell → Step 3C',
    '',
    ':::internal',
    'Treat flashing green PON and solid green PON the same — both indicate provisioning, not a physical line fault.',
    ':::',
    '',
    '## Step 3A: Red LOS — Physical Line Fault',
    '',
    ':::eddie',
    'A red LOS light usually means there\'s a physical issue with the fibre line — it could be a break, a sharp bend, or damage to the cable. Can you check the fibre cable running to your router for any visible bends, kinks, or damage?',
    ':::',
    '',
    '{red|Fibre-LOS}',
    '',
    '- Any result → Step 4',
    '',
    '## Step 3B: Green PON — Provisioning Issue',
    '',
    ':::eddie',
    "Your PON light is green, which means the fibre line itself looks okay — but there may be a provisioning issue on Zoom Fibre's side. I'll need to log this with them to investigate.",
    ':::',
    '',
    '{amber|Fibre-PON}',
    '',
    '- Any result → Step 4',
    '',
    '## Step 3C: Lights Unclear — Request Photo',
    '',
    ':::eddie',
    "No worries — could you take a photo of the front of your router showing the lights, and send it through to me? That'll help me figure out exactly what's going on.",
    ':::',
    '',
    ':::warn Important',
    'Do not attempt to diagnose further without seeing the lights. Wait for the photo.',
    ':::',
    '',
    '- Photo received → Step 5 (escalate)',
    '',
    '## Step 4: Request Photos',
    '',
    ':::eddie',
    'To help our team investigate, could you send me two photos please?',
    '1. The **front** of your router (showing the lights)',
    '2. The **back** of your router (showing the serial number sticker)',
    ':::',
    '',
    ':::internal',
    'Wait for **BOTH** photos before proceeding. Do not escalate with only one.',
    ':::',
    '',
    '{red|Escalate-ZoomFibre}',
    '',
    '- Both photos received → Step 5',
    '',
    '## Step 5: Escalate',
    '',
    ':::eddie',
    "Thanks for sending those through! I've got everything I need. I'm going to flag this for one of our team members to take a closer look and get it sorted for you. Someone will be in touch soon.",
    ':::',
    '',
    ':::warn Never',
    '• Never log a ticket directly with Zoom Fibre',
    '• Never contact Zoom Fibre on behalf of the client',
    '• Never promise an ETA for resolution',
    ':::',
    '',
    '{red|Fibre-LOS} {amber|Fibre-PON} {red|Escalate-ZoomFibre}'
  ].join('\n')
};
