Eddie.playbooks['c'] = {
  id: 'c',
  title: 'Playbook C — No Internet · Wireless',
  subtitle: 'Antenna + PoE diagnosis',
  status: 'active',
  color: 'var(--green)',
  group: 'playbooks',
  keywords: ['wireless', 'no internet', 'antenna', 'PoE', 'WTTH', 'power supply'],
  markdown: [
    '---',
    'title: Playbook C — No Internet · Wireless',
    'subtitle: Antenna + PoE diagnosis',
    'status: active',
    'keywords: wireless, antenna, PoE, WTTH',
    '---',
    '',
    ':::internal Equipment overview',
    'Wireless setup: outdoor antenna + PoE power supply + indoor router. Typical speeds: 4, 5, 6, 8, 10 Mbps.',
    ':::',
    '',
    '## Step 1: Check Router Power Lights',
    '',
    ':::eddie',
    "Let's start by checking your router — are there any lights on it at all?",
    ':::',
    '',
    '- No lights at all → Check wall plug, adapter, UPS',
    '- Lights are on → Step 2',
    '',
    '## Step 2: Check PoE Unit',
    '',
    ':::eddie',
    'Great, your router has power. Now, there should be a small black box (PoE unit) — usually near a plug point, sometimes next to the router. Is it plugged in, and does it have any lights?',
    ':::',
    '',
    '- No lights on PoE → Check plug, adapter, retry',
    '- PoE lights present → Step 3',
    '',
    '## Step 3: Check Cables Both Ends',
    '',
    ':::eddie',
    'Can you check the network cables? There should be one going from the PoE unit to your router, and another from the PoE unit towards the outdoor antenna. Make sure both are plugged in firmly at both ends.',
    ':::',
    '',
    '- Cables confirmed → Step 4',
    '',
    '## Step 4: Restart in Correct Order',
    '',
    ':::eddie',
    "Let's do a full restart in the right order:",
    '1. Switch off your **router**',
    '2. Unplug the **PoE unit**',
    '3. Wait **30 seconds**',
    '4. Plug the **PoE unit** back in',
    '5. Switch on the **router**',
    '6. Wait **2–3 minutes** for everything to reconnect',
    ':::',
    '',
    ':::internal',
    'The order matters — PoE must power up before the router so the antenna gets its signal first.',
    ':::',
    '',
    '- Done → Step 5',
    '',
    '## Step 5: Test Connection',
    '',
    ':::eddie',
    "Alright, can you try loading a website or running a quick speed test now? Let me know if things are working.",
    ':::',
    '',
    '- Working → ✅ RESOLVED',
    '- Still down → Step 6',
    '',
    '## Step 6: Escalate',
    '',
    ':::eddie',
    "I appreciate you going through all of that with me. It looks like this needs a closer look from our technical team. Let me just grab a few details so they can follow up:",
    ':::',
    '',
    ':::internal Collect',
    '• When the issue started',
    '• Whether they restarted equipment',
    '• Whether any lights are present on the PoE/router',
    ':::',
    '',
    ':::warn Never',
    'Never ask the client to touch, climb to, or adjust any roof-mounted or outdoor equipment (antenna, cables on the roof, etc.).',
    ':::',
    '',
    '{red|Escalate-Wireless}'
  ].join('\n')
};
