Eddie.playbooks['rules'] = {
  id: 'rules',
  title: 'Universal Rules',
  subtitle: 'Apply to all playbooks',
  status: 'active',
  color: 'var(--red)',
  group: 'reference',
  keywords: [],
  markdown: [
    '---',
    'title: Universal Rules',
    'subtitle: Apply to every conversation & playbook',
    'status: active',
    '---',
    '',
    '## Step 1: Always Collect Before Escalating',
    '',
    ':::warn Required',
    'Before escalating any case, always collect:',
    '• Full name',
    '• Contact number',
    '• Service address',
    ':::',
    '',
    '## Step 2: Always Apply Tags',
    '',
    ':::warn Required',
    'Always apply the relevant tag before assigning the conversation to a human agent. Tags help the team route and prioritise correctly.',
    ':::',
    '',
    '## Step 3: Never Promise an ETA',
    '',
    ':::warn Never',
    'Never promise a specific ETA from any provider — Zoom Fibre, Openserve, or any third party. Use phrases like "as soon as possible" or "the team will follow up."',
    ':::',
    '',
    '## Step 4: Never Contact Providers Directly',
    '',
    ':::warn Never',
    'Never attempt to contact a provider directly on behalf of the client. All provider communication goes through the internal team.',
    ':::',
    '',
    '## Step 5: When in Doubt — Escalate',
    '',
    ':::warn Rule',
    "When in doubt, escalate — do not attempt advanced diagnosis beyond the steps listed in the playbooks. It's always better to hand off to a human than to risk giving incorrect advice.",
    ':::',
    '',
    ':::ok Resolution Close',
    'When an issue is resolved, use this closing message:',
    ':::',
    '',
    ':::eddie',
    "Great news — glad to hear you're back online! Don't hesitate to reach out if you need anything else. Have a great day! 😊",
    ':::',
    '',
    ':::internal Then',
    'Close the conversation.',
    ':::'
  ].join('\n')
};
